using Game.Estate.UltimaIX.FilePack;
using System.Collections.Generic;

namespace Game.Estate.UltimaIX.Records
{
    public class WRLDRecord : Record
    {
        static Dictionary<int, string> abc = new Dictionary<int, string>
        {
            { 0, "The Lunch Room" },
            { 10, "Shame" },
            { 100, "Demo Above Ground" },
            { 101, "Demo Under Ground" },
            { 102, "Gremlin Demo Map" },
            { 103, "Spider Demo Map" },
            { 104, "Weapon Equipping Demo Map" },
            { 105, "Dina’s Enclosed Mess" },
            { 107, "Aaron test map" },
            { 11, "Abyss" },
            { 118, "Map 118" },
            { 119, "Rands Test Map" },
            { 12, "Tower of Exultation Level 1" },
            { 120, "Crumps personal map" },
            { 121, "junk.21" },
            { 122, "Amy’s Test Map" },
            { 123, "Franzingruven" },
            { 124, "Myque’s Test Map" },
            { 125, "Map 125" },
            { 126, "Dina’s Destard" },
            { 127, "Map 127" },
            { 128, "Amy’s Dungeon Test Map" },
            { 129, "QmazeTest Bill and Scott" },
            { 13, "Tower of Exultation Level 2" },
            { 130, "Dina’s Crazy Map" },
            { 131, "Myque’s Experiment" },
            { 14, "Avatar’s House Earth" },
            { 140, "Gary’s Another Test Map" },
            { 141, "Gary’s Test Dungeon" },
            { 142, "Gary’s Test Map" },
            { 143, "Scott World" },
            { 144, "Herman’s New Gerbilville" },
            { 145, "Herman’s stupid test map" },
            { 146, "Jen’s Joyebean Land" },
            { 147, "Jim’s Happy Evil Map" },
            { 148, "ScottJ’s Cavern Test Map" },
            { 149, "Bill’s Creature Map" },
            { 15, "Asylum Underground" },
            { 150, "Torch Test - Poof!" },
            { 151, "Bill’s Bubba’s World" },
            { 152, "Torch Test - Alpha Bitmap" },
            { 153, "The Map That Keeps Getting Trashed" },
            { 154, "Great Balls o’ Fire!" },
            { 155, "Chuck’s Usecode Test Map" },
            { 156, "Jen’s Test Too" },
            { 157, "Todd’s Test" },
            { 158, "Scottie-cake’s Brave New World" },
            { 159, "Great Balls O’ Fire Underground" },
            { 16, "Covetous Level 0 & 1" },
            { 160, "Creature map" },
            {161, "ScottJ’s Riverbank template" },
            {162, "Margery Must Die" },
            {163, "Dave’s Combat Save/Load test map" },
            {164, "Copy of britannia" },
            {165, "Britain Test" },
            {166, "Seth B Map" },
            {167, "Hutsville (DMA)" },
            {168, "Herman’s scratch copy of Britannia" },
            {169, "Herman’s Other Copy of Britannia" },
            {17, "Covetous Level 2" },
            {170, "Avatar’s House Earth (copy)" },
            {171, "Hassan’s Map" },
            {172, "Combt Audio Test Map" },
            {173, "Seth’s Dungeon O’ Fun" },
            {174, "Seth’s Caverns O’ Fun" },
            {175, "Steve’s Map" },
            {176, "Special Combat Audio Test Map" },
            {179, "Test Map for Scott" },
            {18, "Covetous Level 3" },
            {180, "Bob Dodd’s World O’ Pain" },
            {184, "Jen’s Copy of Cove" },
            {186, "terry’s test map" },
            {187, "Marsh’s New World" },
            {189, "Down the Rabbit Hole (ScottW)" },
            {19, "Covetous Level 4" },
            {192, "Jason’s Map" },
            {193, "Jason’s Map 2" },
            {195, "art’s map test trinsic" },
            {196, "Lord British’s Castle (ScottW)" },
            {198, "Cari’s Finished Characters" },
            {199, "Scott’s Maze" },
            {2, "Asylum" },
            {20, "Covetous Lift Shaft" },
            {200, "Joe’s test map" },
            {201, "Dave’s Sound Test" },
            {202, "Dave’s EAX Sound Test Map" },
            {205, "Victor_Caverns R Us" },
            {207, "Bill’s Lighting Test" },
            {21, "Cove Underground" },
            {211, "Map 211" },
            {213, "Herman’s Wrap Map" },
            {214, "Victor_Map" },
            {215, "Binky’s Map" },
            {216, "Avatar - Raven Contents Test Map" },
            {22, "Ethereal Void" },
            {227, "art’s working map2" },
            {23, "Stonegate Underground" },
            {230, "Copy of Britannia (Don’t change triggers!)" },
            {233, "my map" },
            {235, "Jim BTest. (copy)" },
            {237, "Map 237" },
            {238, "testgenerator" },
            {239, "Jim Test Underground.opy)" },
            {24, "Britain Sewers" },
            {25, "New Despise.ngeon" },
            {26, "Terfin level 1" },
            {27, "New Shame" },
            {28, "Dungeon Destard (old)" },
            {29, "Dungeon Destard (old dragon)" },
            {3, "4 islands" },
            {30, "Covetous 2" },
            {31, "Covetous 3" },
            {32, "Son of Covetous 3" },
            {33, "Son of Covetous 2" },
            {34, "Map 34" },
            {35, "Deceit 1" },
            {36, "Britain Catacombs" },
            {37, "NPC Map Test" },
            {38, "underground moonglow" },
            {39, "Fake Moon Triggers" },
            {4, "Moonglow" },
            {40, "Ambrosia Sweet Ambrosia" },
            {41, "Stonegate Fix" },
            {42, "Map 42" },
            {43, "Deceit 2" },
            {44, "Abyss Dungeon Map" },
            {45, "Wrong" },
            {46, "Terfin dungeon" },
            {47, "New Destard" },
            {48, "Anti-Void" },
            {49, "Castle Prison" },
            {5, "Cove" },
            {50, "Hythloth Upper Levels" },
            {51, "Valley of souls" },
            {52, "Lb/Blackthorn fight" },
            {53, "Scary Monsters" },
            {54, "DropInAbyss" },
            {55, "Bone Armor Ritual Map" },
            {56, "Fake Column Triggers" },
            {57, "Shame" },
            {58, "Ambrosia Sweet Ambrosia copy" },
            {6, "Terfin" },
            {60, "Map 60" },
            {61, "Water" },
            {62, "Air" },
            {63, "Earth" },
            {64, "Fire" },
            {65, "One Small Step" },
            {66, "Hallways of Insanity" },
            {67, "Stonegate Roof" },
            {68, "-" },
            {7, "Trinsic" },
            {70, "SEM Test" },
            {77, "Dragon Highway test" },
            {8, "Valoria" },
            {80, "64 by 64, 20 polys per" },
            {81, "64 by 64, 193 polys per" },
            {82, "64 by 64, misc objects" },
            {83, "64 by 64, chunk crossing items" },
            {84, "64 by 64, high-poly count" },
            {85, "64 by 64, building cluster" },
            {86, "64 by 64 , buildings sparse" },
            {87, "64 by 64, high texrure, low items" },
            {89, "Buc2NewMag" },
            {9, "Britannia" },
            {90, "Mariah’s Basement" },
            {98, "E3 Demo for Real" },
            {99, "E3 Demo Underground" },
        };
    }
}